USE Protheus
GO

SELECT X3_CAMPO, X3_DESCRIC, X3_RELACAO, X3_F3 'CONSULTA_PADRAO', X3_CBOX 'OPCOES' FROM SX3990
WHERE X3_ARQUIVO IN ('ZZA', 'ZZB')
;


SELECT * FROM ZZA990
SELECT * FROM ZZB990
;
